version: '2'

services:
  server:
    image: nginx:1-alpine
    ports:
      - 80
    volumes:
      - ./config/nginx/conf.d:/etc/nginx/conf.d:ro
      - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    volumes_from:
      - phpfpm:ro
    networks:
      - front
      - back
    labels:
      - "SERVICE_80_NAME=wambo.co"
      - "SERVICE_80_TAGS=urlprefix-wambo.co/,urlprefix-www.wambo.co/"
      - "SERVICE_80_CHECK_HTTP=/"
      - "SERVICE_80_CHECK_INTERVAL=10s"
      - "SERVICE_80_CHECK_TIMEOUT=5s"

  phpfpm:
    image: php:7-fpm-alpine
    volumes:
      - ./web:/var/www/html
    networks:
      - back

networks:
  front:
    driver: bridge
  back:
    driver: bridge
