version: '2'

services:
  webserver:
    image: nginx:1-alpine
    ports:
      - 80
    volumes:
      - ./config/nginx/conf.d:/etc/nginx/conf.d:ro
      - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    volumes_from:
      - phpfpm:ro
    labels:
      io.rancher.container.pull_image: always
      io.rancher.sidekicks: phpfpm

  phpfpm:
    image: php:7-fpm-alpine
    volumes:
      - ./web:/var/www/html
    labels:
      io.rancher.container.pull_image: always
