version: '2'

services:
  web:
    image: nginx:1-alpine
    ports:
      - "9080:80"
    volumes:
      - ./config/nginx/conf.d:/etc/nginx/conf.d:ro
      - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./web:/usr/share/nginx/html
    networks:
      - front
      - back

networks:
  front:
    driver: bridge
  back:
    driver: bridge
