version: '2'
services:
  phpfpm:
    image: registry.002.io:5000/andreaskoch/wambo.one-phpfpm:latest
    stdin_open: true
    tty: true
    labels:
      io.rancher.container.pull_image: always
  webserver:
    image: registry.002.io:5000/andreaskoch/wambo.one-webserver:latest
    stdin_open: true
    tty: true
    links:
    - phpfpm:phpfpm
    labels:
      io.rancher.container.pull_image: always
